# Generated by Django 2.2.19 on 2021-04-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210404_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('teacher', models.TextField()),
                ('teacher_country', models.TextField()),
            ],
        ),
    ]
