# Generated by Django 2.2.19 on 2021-04-06 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210406_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
