# Generated by Django 2.2.19 on 2021-04-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210406_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='id',
            new_name='_id',
        ),
    ]
